name: SCANOSS Code Scan

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      branch:
        description: 'Branch name to checkout'
        required: true
        type: string
permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read
jobs:
  checkout-branch:
    runs-on: self-hosted
    steps:
      - name: Checkout specified branch from external repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: Run SCANOSS Code Scan
        uses: scanoss/code-scan-action@v1
        with:
          output.filepath: results.json
          dependencies.enabled: true
          policies: copyleft,undeclared
          policies.halt_on_failure: true
          format: cyclonedx
#      - name: upload to dependency track
#        # uses: rosslight/DependencyTrackChecker@d5784cae089da1a3f3114f151d4841313d05b060
#        uses: rosslight/DependencyTrackChecker@v1.3
#        with:
#          # Dependency-Track hostname
#          server-hostname: http://localhost:8080/
#          # Dependency-Track API key
#          api-key: odt_lbiBLeIV_k03M3TKvnXxOjlY4hExDW835Mcer3h4Z
#          # Project in Dependency-Track
#          project: new-project
#          # Path and filename of the BOM
#          bom-filename: /home/bthamoth/actions-runner/_work/temporary/temporary/result.json
#          # Path and filename to save the output to
#          bom-output-filename: out-bom.xml

      - name: upload to dependency track
        uses: neerajsu/dependency-track-gh-action@v1.0.4
        with:
          serverHostBaseUrl: 'http://localhost:8081/'
          apikey: odt_lbiBLeIV_k03M3TKvnXxOjlY4hExDW835Mcer3h4Z
          projectname: 'new-project'
          projectversion: '0.1.0'
          autocreate: 'true'
          bomFilePath: 'results.json'
          timeoutInSecs: '500'
          prNumber: '1'
