name: SCANOSS Code Scan

on:
  push:
    branches: [ "*" ]
  pull_request:

permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read

jobs:
  scanoss-code-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run SCANOSS Code Scan
        uses: scanoss/code-scan-action@v1
        with:
          output.filepath: results.json
          dependencies.enabled: true
          policies: copyleft,undeclared
          policies.halt_on_failure: true
