name: SCANOSS Code Scan

on:
  workflow_dispatch:
    inputs:
      repository:
        description: 'Repository name (e.g., owner/repo)'
        required: true
        type: string
      branch:
        description: 'Branch name to checkout'
        required: true
        type: string
      project-name:
        description: 'Project name in Dependency track'
        required: true
        type: string
      project-version: 
        description: 'Project version in Dependency Track'
        required: true
        type: string
permissions:
  contents: read
  pull-requests: write
  checks: write
  actions: read
jobs:
  scan-and-upload:
    runs-on: self-hosted
    steps:
      - name: Checkout specified branch from external repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.repository }}
          ref: ${{ inputs.branch }}
      - name: SCANOSS Code Scan Action
        uses: scanoss/gha-code-scan@v1.2.1
        with:
          dependencies.enabled: true
          debug: true
          deptrack.upload: true
          deptrack.url: ${{ secrets.DEPENDENCY_TRACK_API_URL }}
          deptrack.apikey: ${{ secrets.DEPENDENCY_TRACK_API_KEY }}
          deptrack.projectname: ${{ inputs.project-name }}
          deptrack.projectversion: ${{ inputs.project-version }}
          
